volumes:
  autwo_local_postgres_data: {}
  autwo_local_postgres_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: autwo_local_django
    container_name: autwo_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8001:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: autwo_production_postgres
    container_name: autwo_local_postgres
    volumes:
      - autwo_local_postgres_data:/var/lib/postgresql/data
      - autwo_local_postgres_data_backups:/backups
    ports:
      - '5432:5432'
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: autwo_local_mailpit
    ports:
      - "8025:8025"
